upstream_package_name: awscrt
downstream_package_name: python-awscrt

upstream_project_url: https://github.com/awslabs/aws-crt-python
issue_repository: https://github.com/awslabs/aws-crt-python

upstream_tag_template: v{version}

specfile_path: fedora/python-awscrt.spec

files_to_sync:
  - fedora/python-awscrt.spec
  - .packit.yaml

copy_upstream_release_description: true

actions:
  post-upstream-clone:
    - git submodule update --init
  create-archive:
    - bash -c "sed -i \"s/^__version__ = .*/__version__ = \'${PACKIT_PROJECT_VERSION}\'/\" awscrt/__init__.py"
    - python3 -m build --sdist --outdir ./fedora/
    - bash -c "ls -1t ./fedora/*.tar.gz | head -n 1"

srpm_build_deps:
  - python3-build

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-all

  - job: propose_downstream
    trigger: release
    dist_git_branches:
      - fedora-all

  - job: koji_build
    trigger: commit
    dist_git_branches:
      - fedora-all

  - job: bodhi_update
    trigger: commit
    dist_git_branches:
      - fedora-branched # rawhide updates are created automatically
