name: docs

on:
  push:
    branches:
      - 'autodocs'

jobs:
  update-docs:
    runs-on: ubuntu-20.04 # latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update docs
        run: |
          python3 -m pip install sphinx
          python3 -m pip install --verbose .
          ./make-docs.sh

      - name: Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add --force docs/
          git commit --message="update docs"

      - name: Push to docs branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ github.token }}
          branch: docs
          force: true
