name: CI Self-Hosted

on: [push]

jobs:
  Ubuntu:

    runs-on: [self-hosted, linux]

    steps:
    - name: Checkout Source
      uses: actions/checkout@v1
    
    - name: Build and test
      run: |
        export CODEBUILD_SRC_DIR=$(pwd)
        python3 -c "from urllib.request import urlretrieve; urlretrieve('https://raw.githubusercontent.com/awslabs/aws-c-common/builder2/codebuild/builder.py', 'builder.py')"
        python3 builder.py run aws-crt-python
