name: CI Action

on: [push]

jobs:
  Ubuntu:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v1
    
    - name: Build and test
      run: |
        export CODEBUILD_SRC_DIR=$(pwd)
        python3 -m pip install --upgrade virtualenv
        python3 -m virtualenv venv
        python3 -c "from urllib.request import urlretrieve; urlretrieve('https://raw.githubusercontent.com/awslabs/aws-c-common/builder2/codebuild/builder.py', 'builder.py')"
        ./venv/bin/python builder.py run aws-crt-python
