name: CI (Ubuntu 16 x64)

on: [push]

jobs:
  Ubuntu:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v1
    - uses: ./.github/actions/manylinux1-x64
      name: Build and Test
      with:
          spec: linux-clang-9-linux-x64
    
