name: CI

on: [push]

jobs:
  manylinux1-x64:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v1
    - uses: ./.github/actions/manylinux1-x64
      name: Build and Test
      with:
          action: manylinux1-ci
  
  manylinux1-x86:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v1
    - uses: ./.github/actions/manylinux1-x86
      name: Build and Test
      with:
          action: manylinux1-ci    
