name: CI (Ubuntu Docker)

on: [push]

jobs:
  Ubuntu:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v1
    - uses: ./.github/actions/ubuntu-16-x64
      name: Build and Test
      with:
          spec: linux-clang-9-linux-x64
    
